// 預設敏感與機密關鍵字
export const DEFAULT_SENSITIVE_KEYS = [
  'password', 'passwd', 'pwd', 'secret', 'token', 'access_token', 'refresh_token',
  'api_key', 'apikey', 'auth', 'authorization', 'signature', 'sig', 'ssn',
  'client_secret', 'private_key',
];

// 信用卡與 PCI-DSS 支付關鍵字
export const PAYMENT_KEYS = [
  'card_number', 'cardnumber', 'card_no', 'cardno', 'credit_card', 'creditcard',
  'cc_num', 'cc_number', 'pan', 'account_no', 'account_number', 'cvv', 'cvc',
  'cvv2', 'cvc2', 'security_code', 'csc', 'exp_month', 'exp_year', 'expiry',
  'expiration_date', 'card_exp', 'cardholder_name', 'billing_address',
];

// 第三方追蹤分析網域
export const TRACKER_DOMAINS = [
  'google-analytics.com', 'analytics.google.com', 'googletagmanager.com',
  'connect.facebook.net', 'facebook.net/tr', 'hotjar.com', 'sentry.io',
  'browser-intake-datadoghq.com', 'datadoghq.com', 'mixpanel.com',
  'segment.io', 'analytics.tiktok.com', 'clarity.ms',
];

// 示範用 Sample HAR 資料產生器
export function generateSampleHar(): any {
  return {
    log: {
      version: '1.2',
      creator: { name: 'Smalltools HAR Generator', version: '1.0' },
      entries: [
        {
          startedDateTime: '2026-08-22T10:00:00.123Z',
          time: 85,
          request: {
            method: 'POST',
            url: 'https://api.example.com/v1/auth/login?client_id=demo_app&redirect_token=sec_tok_987654321',
            httpVersion: 'HTTP/2.0',
            cookies: [
              { name: 'session_id', value: 'sess_live_98a76b54c3210' },
              { name: 'user_pref', value: 'dark_mode' },
            ],
            headers: [
              { name: 'Host', value: 'api.example.com' },
              { name: 'User-Agent', value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' },
              { name: 'Authorization', value: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ' },
              { name: 'X-Api-Key', value: 'test_mock_apikey_9876543210abcdef' },
              { name: 'Cookie', value: 'session_id=sess_live_98a76b54c3210; token=secret_cookie_token_999; theme=dark' },
              { name: 'Content-Type', value: 'application/json' },
            ],
            queryString: [
              { name: 'client_id', value: 'demo_app' },
              { name: 'redirect_token', value: 'sec_tok_987654321' },
            ],
            postData: {
              mimeType: 'application/json',
              text: JSON.stringify({
                username: 'admin@example.com',
                password: 'SuperSecretP@ssw0rd!2026',
                credit_card: '4532-1234-5678-9012',
                aws_access_key: 'AKIAIOSFODNN7EXAMPLE',
              }, null, 2),
            },
          },
          response: {
            status: 200,
            statusText: 'OK',
            httpVersion: 'HTTP/2.0',
            cookies: [
              { name: 'session_id', value: 'sess_live_new_updated_token_999' },
            ],
            headers: [
              { name: 'Content-Type', value: 'application/json; charset=utf-8' },
              { name: 'Set-Cookie', value: 'session_id=sess_live_new_updated_token_999; Path=/; HttpOnly; Secure' },
            ],
            content: {
              size: 256,
              mimeType: 'application/json',
              text: JSON.stringify({
                status: 'success',
                accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c3JfOTA5MCIsImV4cCI6MTgwMDAwMDAwMH0.K7kK7mQ6lE23fG9h7j2k1L8',
                user: {
                  email: 'admin@example.com',
                  name: 'System Administrator',
                  internal_secret: 'confidential_server_key_888',
                },
              }, null, 2),
            },
          },
        },
        {
          startedDateTime: '2026-08-22T10:00:01.000Z',
          time: 145,
          request: {
            method: 'GET',
            url: 'https://cdn.example.com/assets/hero-banner.png?auth_token=tok_image_secret_123',
            httpVersion: 'HTTP/2.0',
            cookies: [],
            headers: [
              { name: 'Host', value: 'cdn.example.com' },
              { name: 'Accept', value: 'image/png' },
            ],
            queryString: [
              { name: 'auth_token', value: 'tok_image_secret_123' },
            ],
          },
          response: {
            status: 200,
            statusText: 'OK',
            httpVersion: 'HTTP/2.0',
            cookies: [],
            headers: [
              { name: 'Content-Type', value: 'image/png' },
              { name: 'Content-Length', value: '450000' },
            ],
            content: {
              size: 450000,
              mimeType: 'image/png',
              encoding: 'base64',
              text: 'iVBORw0KGgoAAAANSUhEUgAABAAAAAMACAYAAACW0wt...[Extremely Large Base64 Image Payload 450KB]...AAAABJRU5ErkJggg==',
            },
          },
        },
        {
          startedDateTime: '2026-08-22T10:00:02.500Z',
          time: 42,
          request: {
            method: 'POST',
            url: 'https://www.google-analytics.com/g/collect?v=2&tid=G-XXXXX&cid=12345.67890',
            httpVersion: 'HTTP/2.0',
            cookies: [],
            headers: [
              { name: 'Host', value: 'www.google-analytics.com' },
            ],
            queryString: [
              { name: 'v', value: '2' },
              { name: 'tid', value: 'G-XXXXX' },
            ],
          },
          response: {
            status: 204,
            statusText: 'No Content',
            httpVersion: 'HTTP/2.0',
            cookies: [],
            headers: [],
            content: { size: 0, mimeType: 'text/plain' },
          },
        },
      ],
    },
  };
}

// 雙語翻譯字典 (100% 完整覆蓋)
export const TRANSLATIONS = {
  'zh-TW': {
    title: 'HAR 敏感資料清理工具',
    subtitle: 'HAR SANITIZER & PRIVACY CLEANER',
    description:
      '專業純前端 HAR 封包脫敏與瘦身神器！一鍵清除 Cookie、授權 Token、JWT、API 密鑰與敏感個資，並可自動刪除肥大二進位媒體酬載，100% 本機運算守護資安。',
    langToggleUrl: '/har-cleaner/en/',
    langToggleLabel: 'English',
    dropzoneTitle: '拖曳 HAR 檔案至此處，或點擊選擇檔案',
    dropzoneHint: '支援所有標準 HTTP Archive (.har, .json) 檔案，純本機記憶體處理不外傳',
    loadSampleBtn: '載入示範 HAR 封包',
    clearBtn: '清空重置',
    rulesTitle: '脫敏與清理全域規則配置',
    ruleAuthHeaders: '身分認證標頭 (Authorization, Bearer, Basic, X-Api-Key 等)',
    ruleCookies: 'Cookie 與 Session 憑證 (Cookie, Set-Cookie 及 Cookies 陣列)',
    ruleQueryParams: '網址敏感參數 (token, secret, key, password, code 等)',
    rulePostData: 'POST 表單與 JSON Payload 機密欄位 (密碼, 憑據等)',
    ruleCreditCard: '信用卡與支付機密 (卡號、CVV、有效期限與 PCI-DSS 支付欄位)',
    ruleRegexDeep: '正則深度掃描 (JWT Token, AWS Key, Stripe Key, Private Key, Email)',
    ruleStripMedia: '大檔媒體瘦身 (清除圖片/影音/字體 Base64，大幅縮減檔案體積)',
    ruleStripTrackers: '過濾第三方追蹤請求 (Google Analytics, Facebook Pixel, Sentry 等)',
    customKeywordsLabel: '自訂敏感欄位名稱 (逗號或換行分隔)',
    customKeywordsPlaceholder: '例如：client_id, internal_secret, user_ssn, phone_number',
    redactionTextLabel: '脫敏替換文字',
    // 敏感標頭控制區
    headersSectionTitle: '不重複敏感標頭審核與消除控制',
    headersSectionSubtitle: '系統已自動彙整所有命中的敏感標頭，您可以個別決定是否要執行脫敏消除，或取消勾選以保留特定標頭進行除錯。',
    headersColRedact: '脫敏消除',
    headersColName: '標頭名稱 (Header Name)',
    headersColScope: '類型 (Scope)',
    headersColRule: '命中規則 (Matched Rule)',
    headersColCount: '出現次數',
    headersColSample: '範例數值預覽',
    headersSelectAll: '全部脫敏消除',
    headersDeselectAll: '全部保留不消除',
    headersNoSensitiveFound: '封包中未發現任何符合規則的敏感標頭',
    scopeReq: 'Request 請求',
    scopeRes: 'Response 回應',
    scopeBoth: '雙向 (Req & Res)',
    statsTotalRequests: '總請求數',
    statsSanitizedRequests: '已脫敏請求',
    statsRedactedItems: '脫敏項目累計',
    statsSizeChange: '檔案體積變化',
    statsSavings: '容量縮減節省',
    tabSummary: '摘要與脫敏統計',
    tabInspector: '請求詳細檢視器',
    tabRawJson: '乾淨 HAR JSON',
    searchPlaceholder: '搜尋 URL 網址、網域或方法...',
    filterAll: '全部',
    filterSanitizedOnly: '僅顯示已脫敏項目',
    ruleFilterAll: '命中規則: 全部',
    ruleFilterAuth: '身分認證標頭',
    ruleFilterCookies: 'Cookie 與 Session 憑證',
    ruleFilterQuery: '網址 Query 參數',
    ruleFilterPost: 'POST / JSON 機密欄位',
    ruleFilterCard: '信用卡與支付機密 (PCI-DSS)',
    ruleFilterCustom: '自訂敏感欄位',
    ruleFilterRegex: '正則深度掃描',
    ruleFilterMedia: '肥大媒體酬載清理',
    ruleFilterClean: '未脫敏乾淨項目 (Clean)',
    colMethod: '方法',
    colStatus: '狀態',
    colUrl: '請求 URL',
    colTime: '耗時',
    colSanitized: '脫敏標記',
    noMatchingEntries: '沒有符合篩選條件的請求紀錄',
    modalTitle: '請求封包詳細審核與脫敏對照',
    modalTabOverview: '概覽與摘要',
    modalTabRequest: '請求內容 (Request)',
    modalTabResponse: '回應內容 (Response)',
    modalTabRaw: '原始 JSON 對照',
    modalClose: '關閉',
    modalCopyEntryJson: '複製本請求 JSON',
    modalCopyUrl: '複製網址',
    modalCleanedVersion: '脫敏後版本',
    modalOriginalVersion: '原始版本',
    modalTiming: '連線耗時',
    modalMimeType: '資源類型',
    modalTriggersTitle: '本請求觸發之脫敏項目 (Redactions Triggered)',
    modalNoRedactions: '本請求未包含敏感項目，保持原樣',
    modalReqHeadersTitle: 'Request 請求標頭',
    modalResHeadersTitle: 'Response 回應標頭',
    modalQueryParamsTitle: '網址 Query 參數',
    modalPostDataTitle: 'POST 請求酬載 (Payload)',
    modalResBodyTitle: 'Response 回應內文',
    modalNameCol: '名稱 (Name)',
    modalValueCol: '數值 (Value)',
    modalActionCol: '操作',
    copyBtnText: '複製',
    copiedSingle: '已複製',
    breakdownCustomKeys: '自訂敏感欄位命中 (Custom Keywords)',
    breakdownCreditCards: '信用卡與支付機密 (PCI-DSS)',
    noHeaders: '無標頭資料',
    noParams: '無網址參數',
    noBody: '無內文資料',
    downloadBtn: '下載清理後 HAR',
    copyJsonBtn: '複製乾淨 JSON',
    copiedToast: '已複製乾淨 HAR JSON 至剪貼簿！',
    exportReportBtn: '匯出脫敏稽核報告',
    processingText: '正在高效處理與脫敏封包中...',
    faqTitle: '常見問題 (FAQ)',
    faqSubtitle: '深入了解 HAR 檔案架構、脫敏原理與資安最佳實踐',
    faqItems: [
      {
        q: '什麼是 HAR (HTTP Archive) 檔案？為什麼直接分享會有資安風險？',
        a: 'HAR (HTTP Archive) 是一種基於 JSON 的標準格式，用於記錄瀏覽器或客戶端與伺服器之間的所有 HTTP/HTTPS 請求與回應細節：\n\n① 涵蓋高度敏感憑據：\nHAR 檔案會忠實記錄請求發送時的 `Authorization` 標頭 (如 Bearer JWT、Basic Auth)、`Cookie` / `Set-Cookie` (含有使用者的登入 Session ID、購物車與身分識別碼)。\n\n② 容易遭到帳號劫持 (Account Takeover)：\n若未經脫敏即將 HAR 檔上傳至公開 Jira、GitHub Issue 或直接傳送給第三方廠商，攻擊者可藉由 HAR 內的 Cookie 或 Token 直接重放請求 (Replay Attack)，無需密碼即可劫持您的真實帳號。',
      },
      {
        q: '本工具是如何進行脫敏與清理的？我的封包資料會被上傳到伺服器嗎？',
        a: '100% 絕對安全！本工具採用純前端 (Client-Side) 零伺服器架構：\n\n① 記憶體內本機即時處理：\n所有 HAR 解析、正則表達式掃描、JSON 遞迴脫敏與檔案生成皆完全在您的瀏覽器 JavaScript 執行環境中完成。\n\n② 零雲端留存：\n封包內容絕不會透過網路發送到任何後端伺服器或第三方分析平台，即使拔掉網路線（離線狀態）也能順暢使用。',
      },
      {
        q: '什麼是「大檔媒體瘦身 (Media Stripping)」？開啟後有何好處？',
        a: '「大檔媒體瘦身」是本工具極具實用價值的特色功能：\n\n① 解決 HAR 檔案動輒數十 MB 的痛點：\n瀏覽器在錄製 HAR 時，會將所有圖片 (PNG, JPEG, WebP)、字型 (WOFF2)、影片及二進位檔案以 Base64 形式編碼寫入 Response Body，導致檔案體積迅速膨脹至 30MB~100MB。\n\n② 保留關鍵排錯資訊同時大幅減重：\n開啟此選項後，系統會清除這類二進位 Base64 酬載，但完整保留 HTTP 狀態碼 (如 200, 404, 500)、連線時間軸、請求與回應 Headers 以及 JSON API 數據，瞬間將檔案壓縮 90% 以上 (<1MB)，便於郵件寄送與客服上傳。',
      },
      {
        q: '工具支援脫敏哪些敏感欄位與模式？',
        a: '系統內建多層級的智慧偵測引擎：\n\n① 身分認證與標頭：\n自動脫敏 `Authorization`, `Proxy-Authorization`, `X-Api-Key`, `X-Auth-Token`, `Bearer`, `Cookie`, `Set-Cookie` 等。\n\n② 網址與表單機密 Key：\n自動攔截 `token`, `access_token`, `auth`, `api_key`, `secret`, `password`, `code`, `session_id`, `refresh_token` 等。\n\n③ 深度正則掃描 (Deep Regex)：\n自動識別並脫敏 JWT 簽章字串 (`eyJ...`)、AWS Access Key (`AKIA...`)、Stripe 密鑰 (`sk_live_...`)、電子郵件地址與 RSA/OpenSSH 私鑰。',
      },
      {
        q: '清理過後的 HAR 檔案能否重新載入到 Chrome DevTools 或 Postman 中？',
        a: '完全相容！本工具嚴格遵循 W3C HAR 1.2 規格：\n\n① 保持標準 JSON 結構：\n脫敏程序僅替換敏感字串內容（如將值替換為 `[REDACTED]`），絕不破壞 JSON 語法、陣列結構或時間戳記欄位。\n\n② 跨工具完美載入：\n匯出的 `.har` 檔案可直接重新拖曳回 Google Chrome DevTools Network 面板、Charles Proxy、Wireshark、Postman、Fiddler 或 Datadog 中正常檢視與分析。',
      },
      {
        q: '如果我有系統專屬的自訂敏感欄位（如 `customer_ssn`），該如何處理？',
        a: '您可以透過「自訂敏感欄位」功能靈活擴充：\n\n① 自訂關鍵字清單：\n在輸入框中填寫欄位名稱（以逗號或換行分隔），如 `customer_ssn, internal_org_id, pay_secret`。\n\n② 全域自動匹配：\n系統會在 Request Headers、Query 參數、POST Form 表單以及遞迴 JSON Body 中同步比對並自動脫敏該欄位。',
      },
      {
        q: '什麼是「第三方追蹤請求過濾 (Tracker Filter)」？',
        a: '過濾無效噪音請求：\n\n① 排除干擾分析的追蹤代碼：\n在錄製網站操作時，通常會伴隨大量的 Google Analytics, Facebook Pixel, Hotjar, Sentry, Datadog 等遙測封包。\n\n② 提升除錯專注度：\n開啟此功能後，系統可自動剔除這些第三方追蹤請求，讓 HAR 檔案只專注於您要排查的核心業務 API 與系統連線。',
      },
      {
        q: '如何快速驗證本工具的效果？',
        a: '一鍵體驗示範封包：\n\n① 點擊「載入示範 HAR 封包」：\n系統會載入包含真實常見情境（含 Bearer JWT、登入 Cookie、敏感 Query 參數、JSON 密碼與肥大圖片酬載）的測試 HAR。\n\n② 立即檢視對照：\n您可以切換規則開關、檢視請求詳細面板，並觀察檔案大小與脫敏前後的差異高亮。',
      },
    ],
  },
  en: {
    title: 'HAR Sensitive Data Sanitizer',
    subtitle: 'HAR SANITIZER & PRIVACY CLEANER',
    description:
      'Professional client-side HAR privacy scrubber and file size slimmer! Redact cookies, auth tokens, JWTs, API keys, and sensitive payloads with zero server transmission. 100% in-browser security.',
    langToggleUrl: '/har-cleaner/',
    langToggleLabel: '繁體中文',
    dropzoneTitle: 'Drag and drop a HAR file here, or click to browse',
    dropzoneHint: 'Supports all standard HTTP Archive (.har, .json) files. 100% processed in local browser memory.',
    loadSampleBtn: 'Load Sample HAR File',
    clearBtn: 'Clear & Reset',
    rulesTitle: 'Sanitization & Cleaning Configuration',
    ruleAuthHeaders: 'Auth Headers (Authorization, Bearer, Basic, X-Api-Key, etc.)',
    ruleCookies: 'Cookies & Session IDs (Cookie, Set-Cookie headers and cookie arrays)',
    ruleQueryParams: 'Sensitive Query Params (token, secret, key, password, code, etc.)',
    rulePostData: 'POST & JSON Payloads (password, credentials, etc.)',
    ruleCreditCard: 'Credit Cards & Payment Data (Card No, CVV, Expiry, PCI-DSS)',
    ruleRegexDeep: 'Deep Regex Scanning (JWT Tokens, AWS Keys, Stripe Keys, Private Keys, Emails)',
    ruleStripMedia: 'Strip Heavy Media Payloads (Removes Base64 images/videos to shrink file size)',
    ruleStripTrackers: 'Filter 3rd-Party Trackers (Google Analytics, Facebook Pixel, Sentry, etc.)',
    customKeywordsLabel: 'Custom Sensitive Field Keys (comma or newline separated)',
    customKeywordsPlaceholder: 'e.g. client_id, internal_secret, user_ssn, phone_number',
    redactionTextLabel: 'Redaction Replacement Text',
    // Unique Headers Section
    headersSectionTitle: 'Unique Sensitive Headers Audit & Control',
    headersSectionSubtitle: 'Review all unique sensitive headers detected across requests. Toggle individual headers to sanitize or preserve intact for troubleshooting.',
    headersColRedact: 'Redact',
    headersColName: 'Header Name',
    headersColScope: 'Scope',
    headersColRule: 'Matched Rule',
    headersColCount: 'Count',
    headersColSample: 'Sample Value',
    headersSelectAll: 'Redact All',
    headersDeselectAll: 'Keep All (No Redact)',
    headersNoSensitiveFound: 'No sensitive headers matching the active rules were found in this archive.',
    scopeReq: 'Request',
    scopeRes: 'Response',
    scopeBoth: 'Both (Req & Res)',
    statsTotalRequests: 'Total Requests',
    statsSanitizedRequests: 'Sanitized Requests',
    statsRedactedItems: 'Redacted Items',
    statsSizeChange: 'File Size Change',
    statsSavings: 'Size Reduction',
    tabSummary: 'Overview & Stats',
    tabInspector: 'Entries Inspector',
    tabRawJson: 'Clean HAR JSON',
    searchPlaceholder: 'Search URL, domain, or method...',
    filterAll: 'All',
    filterSanitizedOnly: 'Sanitized Entries Only',
    ruleFilterAll: 'Rule: All Categories',
    ruleFilterAuth: 'Auth Headers',
    ruleFilterCookies: 'Cookies & Session',
    ruleFilterQuery: 'Query Parameters',
    ruleFilterPost: 'POST / JSON Payloads',
    ruleFilterCard: 'Credit Cards & Payment (PCI-DSS)',
    ruleFilterCustom: 'Custom Keywords',
    ruleFilterRegex: 'Deep Regex Matching',
    ruleFilterMedia: 'Media Stripped',
    ruleFilterClean: 'Unsanitized / Clean',
    colMethod: 'Method',
    colStatus: 'Status',
    colUrl: 'Request URL',
    colTime: 'Time',
    colSanitized: 'Sanitized',
    noMatchingEntries: 'No request entries match the current filter criteria.',
    modalTitle: 'Entry Details Audit & Redaction Inspector',
    modalTabOverview: 'Overview & Diff',
    modalTabRequest: 'Request Content',
    modalTabResponse: 'Response Content',
    modalTabRaw: 'Raw JSON Diff',
    modalClose: 'Close',
    modalCopyEntryJson: 'Copy Entry JSON',
    modalCopyUrl: 'Copy URL',
    modalCleanedVersion: 'Cleaned Version',
    modalOriginalVersion: 'Original Version',
    modalTiming: 'Timing',
    modalMimeType: 'Content Type',
    modalTriggersTitle: 'Redaction Triggers Detected',
    modalNoRedactions: 'No sensitive data detected in this entry. Kept intact.',
    modalReqHeadersTitle: 'Request Headers',
    modalResHeadersTitle: 'Response Headers',
    modalQueryParamsTitle: 'Query Parameters',
    modalPostDataTitle: 'POST Body / Payload',
    modalResBodyTitle: 'Response Body',
    modalNameCol: 'Name',
    modalValueCol: 'Value',
    modalActionCol: 'Action',
    copyBtnText: 'Copy',
    copiedSingle: 'Copied',
    breakdownCustomKeys: 'Custom Sensitive Field Hits',
    breakdownCreditCards: 'Credit Cards & Payment Hits (PCI-DSS)',
    noHeaders: 'No headers found',
    noParams: 'No query parameters',
    noBody: 'No body content',
    downloadBtn: 'Download Cleaned HAR',
    copyJsonBtn: 'Copy Clean JSON',
    copiedToast: 'Cleaned HAR JSON copied to clipboard!',
    exportReportBtn: 'Export Audit Report',
    processingText: 'Sanitizing and processing archive in local memory...',
    faqTitle: 'Frequently Asked Questions (FAQ)',
    faqSubtitle: 'Learn more about HAR structure, privacy redaction, and security best practices',
    faqItems: [
      {
        q: 'What is a HAR (HTTP Archive) file, and why is sharing it risky?',
        a: 'A HAR (HTTP Archive) file is a standard JSON-formatted log containing comprehensive records of HTTP/HTTPS communications between a browser and servers:\n\n① Contains Highly Sensitive Credentials:\nHAR files faithfully record `Authorization` headers (Bearer tokens, Basic auth), session `Cookie` / `Set-Cookie` identifiers, API keys, and request/response payloads.\n\n② Account Takeover Risk:\nIf an un-sanitized HAR is shared with support desks, posted on GitHub, or shared with vendors, attackers can extract session cookies or tokens to replay requests and hijack active user sessions without credentials.',
      },
      {
        q: 'How does this tool sanitize HAR files? Is my data uploaded anywhere?',
        a: '100% Private & Safe! This tool operates entirely on a Zero-Server client-side architecture:\n\n① In-Memory Local Processing:\nAll JSON parsing, regex pattern matching, field scrubbing, and file generation execute strictly inside your local browser memory.\n\n② Zero Network Transmission:\nYour archive contents are never transmitted to any remote servers, cloud endpoints, or third-party telemetry services. It works seamlessly even when offline.',
      },
      {
        q: 'What is "Media Stripping" and how does it reduce file size?',
        a: 'Media Stripping is a powerful feature designed to tackle bloated HAR archives:\n\n① Solves Huge File Sizes:\nWhen recording web sessions, browsers serialize images (PNG, JPEG, WebP), fonts (WOFF2), and binary assets into massive Base64 strings inside Response Bodies, inflating files to 30MB-100MB+.\n\n② Retains Critical Diagnostics while Slashing File Size:\nEnabling this option strips heavy Base64 media data while perfectly preserving HTTP status codes, network timing, request/response headers, and JSON API payloads—typically shrinking the file by over 90% (<1MB).',
      },
      {
        q: 'Which sensitive patterns and fields are automatically sanitized?',
        a: 'The engine features multi-tier automated detection:\n\n① Authentication & Headers:\nRedacts `Authorization`, `Proxy-Authorization`, `X-Api-Key`, `X-Auth-Token`, `Bearer`, `Cookie`, `Set-Cookie`, and session identifiers.\n\n② URL & Form Keys:\nIntercepts `token`, `access_token`, `auth`, `api_key`, `secret`, `password`, `code`, `session_id`, and `refresh_token`.\n\n③ Deep Regex Detection:\nDetects and masks JWT signatures (`eyJ...`), AWS Access Keys (`AKIA...`), Stripe keys (`sk_live_...`), emails, and RSA/OpenSSH private keys.',
      },
      {
        q: 'Can the cleaned HAR file be re-imported into Chrome DevTools or Postman?',
        a: 'Fully Compatible! The tool strictly adheres to the W3C HAR 1.2 specification:\n\n① Preserves JSON Integrity:\nSanitization modifies sensitive string values (e.g. replacing them with `[REDACTED]`) without altering object hierarchies, timestamps, or required structure.\n\n② Seamless Multi-Tool Support:\nExported `.har` files can be immediately dragged back into Chrome DevTools Network tab, Charles Proxy, Wireshark, Postman, Fiddler, or Datadog for continued troubleshooting.',
      },
      {
        q: 'How can I add custom sensitive fields specific to my company or app?',
        a: 'You can easily configure custom rules:\n\n① Custom Keywords List:\nEnter field names (comma or newline separated) such as `customer_ssn, internal_org_id, pay_secret`.\n\n② Global Automatic Matching:\nThe scrubber will automatically redact these keys across Request Headers, Query parameters, POST form bodies, and nested JSON objects.',
      },
      {
        q: 'What does the "Tracker Filter" option do?',
        a: 'Eliminates telemetry noise:\n\n① Removes Third-Party Analytics Requests:\nRecorded browser sessions often contain dozens of tracking beacons from Google Analytics, Facebook Pixel, Hotjar, Sentry, Datadog, etc.\n\n② Focuses on Core APIs:\nEnabling this filter purges these irrelevant telemetry requests so you can focus purely on your application\'s primary endpoints.',
      },
      {
        q: 'How can I quickly try out and test this tool?',
        a: 'One-Click Sample Experience:\n\n① Click "Load Sample HAR File":\nThe tool will immediately load a realistic sample HAR containing JWTs, auth cookies, sensitive query params, and image payloads.\n\n② Real-time Inspection:\nToggle cleaning rules, view entry diffs, and observe instant file size reduction and sanitization statistics.',
      },
    ],
  },
};
